File.cwd!()
|> Path.join("2021/01/input.txt")
|> File.read!()
|> String.split("\n", trim: true)
|> Enum.map(&String.to_integer/1)
|> Enum.chunk_every(3, 1, :discard)
|> Enum.map(&Enum.sum/1)
|> Enum.chunk_every(2, 1, :discard)
|> Enum.reduce(0, fn [a, b], num -> if(b > a, do: num + 1, else: num) end)
|> IO.inspect()
